### ISSUE TITLE
Feature Request: Exclude folder or files

### ISSUE THREAD

**Issue by jerviscui** [Canna71/obsidian-chronology#29]
![image](https://github.com/Canna71/obsidian-chronology/assets/6396748/18cc037d-82b6-474b-a81f-14c6d1b882e6)

> ment.min.js:2 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
> Arguments: 
> [0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: <% tp.file.creation_date("yyyy-MM-DDTHH:mm:ssZ") %>, _f: undefined, _strict: undefined, _locale: [object Object]
> Error
>     at Function.createFromInputFallback (app://obsidian.md/lib/moment.min.js:2:3257)
>     at Ea (app://obsidian.md/lib/moment.min.js:2:21634)
>     at Fa (app://obsidian.md/lib/moment.min.js:2:22211)
>     at S (app://obsidian.md/lib/moment.min.js:2:22294)
>     at M (app://obsidian.md/lib/moment.min.js:2:207)
>     at eval (plugin:chronology:13:59547)
>     at Array.reduce (<anonymous>)
>     at Hl.getNotesForCalendarItem (plugin:chronology:13:59286)
>     at hf (plugin:chronology:13:68064)
>     at tu (plugin:chronology:11:19504)
> X @ moment.min.js:2

The reason for the problem is:
chronology scan all files.
And I have a Templater plugin file, the string `<% tp.file.last_modified_date("yyyy-MM-DDTHH:mm:ssZ") %>` is a placeholder, but chronology parses it as a Date.

**Comment by Canna71** [comment]
Fixed in 1.1.15
